### ISSUE TITLE
Illuminate not working

### ISSUE THREAD

**Issue by augustoolucas** [LunarVim/nvim-basic-ide#100]
Hello there! The Illuminate plugin is not working for me. When I run ` :IlluminateDebug`, I get the following output:

```
buf_should_illuminate 1 false
config {
  delay = 200,
  filetype_overrides = {},
  filetypes_allowlist = {},
  filetypes_denylist = { "dirvish", "fugitive", "alpha", "NvimTree", "packer", "neogitstatus", "Trouble", "lir", "Outline", "spectre_panel", "toggleterm", "DressingSelect", "TelescopePrompt" },
  modes_allowlist = {},
  modes_denylist = {},
  providers = { "lsp", "treesitter", "regex" },
  providers_regex_syntax_allowlist = {},
  providers_regex_syntax_denylist = {},
  under_cursor = true
}
started true
provider table: 0x7f486c54fc60 lsp
```

I tried` :IlluminateResume/ResumeBuf/Toggle/ToggleBuf` but it didn't work either. Any ideas on what is causing this?

**Comment by kiyoon** [comment]
No idea about the bug but illuminate has some changes on their new version I realised recently. You need to remove the illuminate.on_attach part in `lsp/handler.lua`. Even if you don't delete it it may work but I saw problems with it eg. LSP being extremely slow.

**Comment by Rishabh672003** [comment]
its working in the lazy port https://github.com/LunarVim/nvim-basic-ide/tree/lazy

i guess use it
