### ISSUE TITLE
Show Inline errors

### ISSUE THREAD

**Issue by zdravko61** [LunarVim/nvim-basic-ide#101]
Hey,

Im trying to set inline errors from eslint.

I added eslint_d as a null-ls formatter, then I set virtual_text to true in lsp handlers. Linter is working as expected and I can format code, but doesn't show inline errors.

Any ideas what I'm missing ? 

Example:

1. I open a project ts file and add a few empty lines
2. There is no indication that the empty space is a error. (eslint is configured with prettier to show it this way)
3. When I format empty space is removed 

This exact behaviour shows an error in vscode and sublime.

**Comment by AntDavidLima** [comment]
Hey Zdravko,

eslint can work either as formatting and as diagnostics tools.

To get the inline errors I had to set it as a diagnostics tools on null-ls config.
