### ISSUE TITLE
Rust analyzer configuration not working ?

### ISSUE THREAD

**Issue by rokonio** [LunarVim/nvim-basic-ide#106]
I installed rust-analyzer using Mason and created a rust_analyzer.lua settings file in lua/lsp/settings. I then added rust analyzer to the servers list in mason.lua. I'm trying to change the check command to use clippy instead of cargo check, but it's not working. Here is my rust_analyzer.lua settings:
```lua
return {
  settings = {
    ["rust-analyzer"] = {
      checkOnSave = {
        command = "clippy",
      },
    },
  },
}
``` 
[My full lsp config folder](https://github.com/rokonio/dotfiles/tree/c94ea3bb3e5f59e59a25a36fe6ed8f4c1c096ebc/nvim/lua/user/lsp).

On a unrelated not, does anyone know how to enable the on save ?

**Comment by dox4** [comment]
use `"rust_analyzer"` instead.
