### ISSUE TITLE
illuminate not work

### ISSUE THREAD

**Issue by suinming** [LunarVim/nvim-basic-ide#11]
I found that illuminate is not working on my computer and the terminal kept throwning the error messages. I am using Ubuntu22.04.
![image](https://user-images.githubusercontent.com/86294140/175292909-3abb5a69-2b99-41c6-b743-7a540a4807de.png)

**Comment by ChristianChiarulli** [comment]
That's odd. Try `LuaCacheClear` and also `:PackerSync` `PackerCompile`

**Comment by suinming** [comment]
Thanks for your reply!! I type :PackerSync and the illuminate start working!
I want to know how to try LuaCacheClear as you suggest?

**Comment by ChristianChiarulli** [comment]
Was that not an option as a command?

**Comment by suinming** [comment]
It is an option but I press enter nothing happen .
I wonder if i misunderstand the command you suggest
