### ISSUE TITLE
Is access to command line history broken?

### ISSUE THREAD

**Issue by 1ofseven** [LunarVim/nvim-basic-ide#110]
Using a plain vanilla install any attempt to open the command line history (q: or :^f) results in a flash to the window as if q: or :^f were not pressed. This prevents copying previous commands. The arrow keys do work for single line history movement as usual. shada file has some commands, but not all, such as provided by :hist c but this does not allow copying commands.

**Comment by gBopHuk** [comment]
I join the question in the topic of issue. Is this a feature or bug?  The q: is my common useful tool.
If this a feature what is an alternative of  "q:" ( aka "q colon")  in nvim-base-ide?

**Comment by gBopHuk** [comment]
OK I found the code that handles the CmdWinEnter in user.autocommands.lua and commented it.
What is an alternative way of work with vim-cmd-commands in nvim-basic-ide if the original way is switched off intentionally?

**Comment by 1ofseven** [comment]
Thanks for the lead to the CmdWinEnter routine in autocommands.lua. Not sure what the intent is to disable the feature; possibly a keymapping conflict.

**Comment by Rishabh672003** [comment]
will fix this

**Comment by Rishabh672003** [comment]
should be fixed now
