### ISSUE TITLE
squares instead of icons when doing "nvim ."

### ISSUE THREAD

**Issue by segfaultDelirium** [LunarVim/nvim-basic-ide#113]
Hello
I'm having squares instead of icons when I enter "nvim ."
![image](https://user-images.githubusercontent.com/82722872/218272663-163f24e8-0074-4865-99e4-cf779000e9bb.png)
I'm using kde plasma on opensuse and my terminal is Konsole. 
Konsole font is set to DejaVu Sans Mono 9pt (which I checked supports utf-8). I've also checked the locale and they are all utf-8.
![image](https://user-images.githubusercontent.com/82722872/218272733-d2f76d37-d59d-4848-a225-7af35aac138b.png)
What can I do to see the icons instead of squares?
Thanks

**Comment by robsonpeixoto** [comment]
https://github.com/LunarVim/nvim-basic-ide#fonts
Is recommended use a [Nerd Font](https://www.nerdfonts.com/).
Probably the error is because of that.

**Comment by segfaultDelirium** [comment]
> https://github.com/LunarVim/nvim-basic-ide#fonts Is recommended use a [Nerd Font](https://www.nerdfonts.com/). Probably the error is because of that.

Yes, that works! Thank you <3
