### ISSUE TITLE
Error with a fresh install

### ISSUE THREAD

**Issue by bistace** [LunarVim/nvim-basic-ide#119]
Hello and thank you for putting up this config for Neovim newbies like me!

I have followed the instructions in the Readme for compiling Neovim and installing the config but everytime I start up Neovim (CentOS 7, gnu 8.3.0), I get the following error:
```
               Erreur détectée en traitant /env/export/home/bistace/.config/nvim/init.lua :
E5113: Error while calling lua chunk: ...port/home/bistace/.config/nvim/lua/user/lsp/handlers.lua:10: attempt to call field 'default_capabilities' (a nil value)
stack traceback:
        ...port/home/bistace/.config/nvim/lua/user/lsp/handlers.lua:10: in main chunk
        [C]: in function 'require'
        .../export/home/bistace/.config/nvim/lua/user/lsp/mason.lua:40: in main chunk
        [C]: in function 'require'
        /env/export/home/bistace/.config/nvim/lua/user/lsp/init.lua:6: in main chunk
        [C]: in function 'require'
        /env/export/home/bistace/.config/nvim/init.lua:21: in main chunk
```

Is there something that I could to fix this error?

**Comment by m41t** [comment]
I am having the same error in a clean install.

**Comment by KazmirBO** [comment]
The reason is the file "handlers.lua", and the exact change in line 10
`update_capabilities`
converted to
`default_capabilities`

**Comment by Rishabh672003** [comment]
with the latest update this shouldnt be an issue, closing this for now
