### ISSUE TITLE
Document thinking behind structure and naming conventions

### ISSUE THREAD

**Issue by gbroques** [LunarVim/nvim-basic-ide#121]
Hi, thanks for the work on this project. It's been immensely helpful to me on my Neovim journey as I recently switched from VS Code.

Can we document the thinking behind the structure and naming conventions?

For example, there are some modules in `lua/` like `Lazy`, `autocommands`, `keymaps`, and `options`.

While modules to configure plugins reside in `lua/user` with the same name as the plugin.

As someone new to Neovim, it's not obvious that we namespace these under `user/` to avoid conficts with the plugin itself.

Also, it seems `autocommands`, `keymaps`, and `options` could have been in `user` which was the case for the older [Neovim-from-scratch](https://github.com/LunarVim/Neovim-from-scratch/tree/master/lua/user).

Why the change? Does it have something to do with [Lazy](https://github.com/LunarVim/nvim-basic-ide/blob/master/lua/Lazy.lua#L18)?

Why include "lazy.nvim" over "packer.nvim" like [Neovim-from-scratch](https://github.com/LunarVim/Neovim-from-scratch/blob/master/lua/user/plugins.lua#L43) had?

What about a brief explanation of `settings` and `utils`?
In [Neovim-from-scratch](https://github.com/LunarVim/Neovim-from-scratch/tree/master/lua/user/lsp/settings), `settings` was in `lua/user/lsp/settings` instead of `lua/settings`.

Anyways, some further explanation about the structure of the project and naming conventions would help someone like me who's brand new to Neovim.

Thank you!

**Comment by MickTheRus** [comment]
I'm considering writing a wiki for it to explain our choices in naming convention, file, etc.

**Comment by MickTheRus** [comment]
@gbroques I've made a wiki for all the topics described there. Right now it only has the lazy VS packer, I'm currently working on the config tree and explaining what different parts do

**Comment by MickTheRus** [comment]
https://github.com/LunarVim/nvim-basic-ide/wiki/config_tree

**Comment by gbroques** [comment]
Thank you for your work on this @MickTheRus.

I think we can close this out.

I'll have a read, and see what I can learn! :)

**Comment by Rishabh672003** [comment]
@gbroques i also made a wiki for adding new plugins https://github.com/LunarVim/nvim-basic-ide/wiki/adding_new_plugins
if you have any suggestion do open issue or reply here, its my first time making a doc so yeah
