### ISSUE TITLE
Comment not work with lazy version

### ISSUE THREAD

**Issue by dongdongbh** [LunarVim/nvim-basic-ide#122]
I upgraded to nvim 0.9 lazy release, the comment plugin seems not working. Typing `gcc` or any comment keybinding does nothing, but Lazy shows the `comment` plugin already loaded.

**Comment by dongdongbh** [comment]
I just tested it on lua files. According [Comment.nvim](https://github.com/numToStr/Comment.nvim), the default is `gcc`. I used it before upgrade to last release, it works fine.

**Comment by MickTheRus** [comment]
> I just tested it on lua files. According [Comment.nvim](https://github.com/numToStr/Comment.nvim), the default is `gcc`. Before upgrading to last release, it just worked. And the / is for search in vim.

I must've mistyped, my bad. I meant '<space>/'

**Comment by dongdongbh** [comment]
But why is not `gcc` but `leader+/`, how can I change it back to [Comment.nvim](https://github.com/numToStr/Comment.nvim) 's default?

**Comment by dongdongbh** [comment]
I made it worked by adding following two lines to `M.config()` function 
```lua
  local comment = require "Comment"
  comment.setup();
```
in https://github.com/LunarVim/nvim-basic-ide/blob/master/lua/user/comment.lua
