### ISSUE TITLE
How to re-add the nvim-lsp diagnostic ui styling?

### ISSUE THREAD

**Issue by madhermit** [LunarVim/nvim-basic-ide#126]
Thanks for the big refactor! 

Looks like styling for the [lsp diagnostics ui ](https://github.com/LunarVim/nvim-basic-ide/blob/b9c960ab4009bb165c7601fdb303fceef477d130/lua/user/lsp/handlers.lua#L12) was lost. 
Where and how would I go about adding that back to the config?

Thanks!

**Comment by Rishabh672003** [comment]
download this file https://github.com/Rishabh672003/Neovim/blob/main/lua/rj/lsp/diagnostic.lua
and require it in `init.lua` that should set you the previous diagnostic

**Comment by Rishabh672003** [comment]
i re-added back the previous diagnostic way, so this should be

**Comment by madhermit** [comment]
Awesome thanks!
