### ISSUE TITLE
[Question] How to make everything transparent

### ISSUE THREAD

**Issue by ArifulProtik** [LunarVim/nvim-basic-ide#13]
Hello, 
I am new in lua, can anyone tell me how to make everything transparent?

**Comment by kobzar** [comment]
This is not lua, or this repo question. 
you can find answers in google. 
close the issue please.

**Comment by TJohn0312** [comment]
If your still wondering, here's how i did it

in colorschemes.lua:
require( "tokyonight" ) . setup({
transparent= true,
styles = {
sidebars = "transparent" ,
floats = "dark" ,
}

lualine.lua was more of a pain, so i have a colors function at the top

local colors = {
innerbg = nil, --transparent
outerbg = "#16161D" ,
darkgrey = "#16161d" ,
grey = "#727169"
normal = "#1cafc9" ,
insert = "#DE07A7 ,
visual = "#16C60C" ,
replace = "#fe0065" ,
command = "#f7c900"

then call the function where needed
mine is in :
lualine.setup {
       options = {
                theme = {
                          inactive = {
                                 a = { fg = colors.grey, bg = colors.innerbg, gui = "bold" },
                                 b = { fg = colors.grey, bg = colors.innerbg },
                                 c = { fg = colors.grey, bg = colors.innerbg },
                                 x = { fg = colors.grey, bg = colors.innerbg },
                                 y = { fg = colors.grey, bg = colors.innerbg },
                                 z = { fg = colors.grey, bg = colors.innerbg },
                                 },
                          normal= {
                                 a = { fg = colors.darkgrey, bg = colors.normal, gui = "bold" },
                                 b = { fg = colors.grey, bg = colors.innerbg },
                                 c = { fg = colors.grey, bg = colors.innerbg },
                                 x = { fg = colors.grey, bg = colors.innerbg },
                                 y = { fg = colors.grey, bg = colors.innerbg },
                                 z = { fg = colors.darkgrey, bg = colors.normal},
                                 },
etc..
i've also done this with insert, visual, replace, and command modes.
