### ISSUE TITLE
Update nerd-fonts icons

### ISSUE THREAD

**Issue by alanfvn** [LunarVim/nvim-basic-ide#131]
Nerd fonts released the [3.0.0](https://github.com/ryanoasis/nerd-fonts/releases/tag/v3.0.0) version which dropped support for `nf-mdi-*` class names, this makes some icons to render improperly.

Some of the plugins getting affected by this update include:
- cmp
- lsp
- dap
- lualine

![Screenshot 2023-05-20 195959](https://github.com/LunarVim/nvim-basic-ide/assets/29936954/4bdae145-458a-4ee9-a121-43bbdbf0c37e)

**Comment by Rishabh672003** [comment]
oh this is a problem, i didnt noticed it because i didnt installed the latest nerd fonts, I will try to fix this by latest

**Comment by Rishabh672003** [comment]
Hey @alanfvn can you test this branch https://github.com/LunarVim/nvim-basic-ide/tree/nerd-font-fix 
i have fixed all the nerd icons in cmp.lua, if there are any more in other place please let me know

**Comment by alanfvn** [comment]
Thanks @Rishabh672003, tried the branch and everything is looking good on my end! 🙌

# Alpha
![alpha](https://github.com/LunarVim/nvim-basic-ide/assets/29936954/1cc28511-e645-407d-ae7d-fbbd75223507)
# Cmp
![cmp](https://github.com/LunarVim/nvim-basic-ide/assets/29936954/3f531571-9720-428c-aca0-8ba896e07089)
# Dap
![dap_ui](https://github.com/LunarVim/nvim-basic-ide/assets/29936954/59381c00-d8a4-4ee5-8a2b-0578901f668c)
# Dev-icons
![dev-icons](https://github.com/LunarVim/nvim-basic-ide/assets/29936954/dcf285a7-3335-4065-9bf5-ae0622cb3054)
# Lsp
![lsp](https://github.com/LunarVim/nvim-basic-ide/assets/29936954/fab7aeb6-325b-4827-8b52-0deaf6622138)
# Lualine
![lualine](https://github.com/LunarVim/nvim-basic-ide/assets/29936954/5f343884-4a19-4b26-ad72-46aa52ec9b0c)
# Mason
![mason](https://github.com/LunarVim/nvim-basic-ide/assets/29936954/9a4318cf-d3c0-4878-b97a-ae6a4657bbbd)
# Nvim-tree
![nvim-tree](https://github.com/LunarVim/nvim-basic-ide/assets/29936954/9fc93832-b2be-461f-b368-801f581ea250)
# Telescope
![telescope](https://github.com/LunarVim/nvim-basic-ide/assets/29936954/fac0b523-3643-4dd5-9055-f0d5fe4c7fbc)

**Comment by Rishabh672003** [comment]
nice, thank you very much, will merge that branch so closing this issue now
