### ISSUE TITLE
Can't get LSP-related keybinds to work in Rust buffers while using `rust-analyzer`.

### ISSUE THREAD

**Issue by zeroDivisible** [LunarVim/nvim-basic-ide#132]
Hi there. I tried installing `rust-analyzer` (through `Mason`) and [adding it to servers in init.lua](https://github.com/LunarVim/nvim-basic-ide/blob/master/lua/utils/init.lua#L3) (as "rust_analyzer", with an underscore).

Would I be right saying that after doing this, I should expect having the [LSP related keybinds](https://github.com/LunarVim/nvim-basic-ide/blob/master/lua/user/lsp.lua#L19-L36) defined in Rust buffers? LSP works overall and I know that because I can manually call i.e. `:lua vim.lsp.buf.references()`. However, the keybinds are not getting defined and I'm unsure if I'm missing some setup here.

**Comment by Rishabh672003** [comment]
show me a way to reproduce your issue

**Comment by Rishabh672003** [comment]
closing this as i got no reply, reopen if you want
