### ISSUE TITLE
Failed to run `config` for nvim-tree.lua

### ISSUE THREAD

**Issue by rikkiemariko** [LunarVim/nvim-basic-ide#135]
I'm trying to set up nvim enviroment locally on a Ubuntu server.
After I type nvim, I got error messages below. How can I fix this?

Failed to run `config` for nvim-tree.lua
...k/.local/share/nvim/lazy/nvim-tree.lua/lua/nvim-tree.lua:6: module 'nvim-tree.commands' not found:
^Ino field package.preload['nvim-tree.commands']
cache_loader: module nvim-tree.commands not found
cache_loader_lib: module nvim-tree.commands not found
^Ino file './nvim-tree/commands.lua'
^Ino file '/home/myusrname/.local/src/neovim/.deps/usr/share/luajit-2.1.0-beta3/nvim-tree/commands.lua'
^Ino file '/usr/local/share/lua/5.1/nvim-tree/commands.lua'
^Ino file '/usr/local/share/lua/5.1/nvim-tree/commands/init.lua'
^Ino file '/home/myusrname/.local/src/neovim/.deps/usr/share/lua/5.1/nvim-tree/commands.lua'
^Ino file '/home/myusrname/.local/src/neovim/.deps/usr/share/lua/5.1/nvim-tree/commands/init.lua'
^Ino file './nvim-tree/commands.so'
^Ino file '/usr/local/lib/lua/5.1/nvim-tree/commands.so'
^Ino file '/home/myusrname/.local/src/neovim/.deps/usr/lib/lua/5.1/nvim-tree/commands.so'
^Ino file '/usr/local/lib/lua/5.1/loadall.so'
^Ino file './nvim-tree.so'
^Ino file '/usr/local/lib/lua/5.1/nvim-tree.so'
^Ino file '/home/myusrname/.local/src/neovim/.deps/usr/lib/lua/5.1/nvim-tree.so'
^Ino file '/usr/local/lib/lua/5.1/loadall.so'
# stacktrace:
  - user/nvim-tree.lua:9 _in_ **config**

**Comment by Rishabh672003** [comment]
whats your `nvim` version? on my end everything is working fine with nvim 0.9 so make sure you are on that version

**Comment by rikkiemariko** [comment]
I see! My nvim version is 0.9.1. When I set up in nvim 0.9 on another PC, it worked, so maybe that's why.
