### ISSUE TITLE
Question: What's the recommended way to manage custom changes?

### ISSUE THREAD

**Issue by shijialee** [LunarVim/nvim-basic-ide#139]
Hi, 

I have been using nvim-base-ide since last October and accumulated some changes. It has been working great. Now I am having trouble installing terraform-ls, but it installed fine under the new nvim-basic-ide. 

If I upgrade to the latest, What's the recommended way to migrate my changes?  What's the best practice going forward?

FYI, I have made changes to the following file

```
lua/user/autocommands.lua
lua/user/bufferline.lua
lua/user/keymaps.lua
lua/user/lsp/mason.lua
lua/user/lualine.lua
lua/user/options.lua
lua/user/plugins.lua
```

Thanks!

James

**Comment by MickTheRus** [comment]
under
```lua/utils/init.lua```
add it to the list of the servers.

**Comment by Rishabh672003** [comment]
@shijialee for already existant plugins look into there respective files and copy your config there.
if you want to add more plugins look into https://github.com/LunarVim/nvim-basic-ide/wiki/adding_new_plugins
for more lsp servers add them to `utils.lua`

**Comment by Rishabh672003** [comment]
my answer should be sufficient , reopen the issue if it isnt

**Comment by PorcelainMouse** [comment]
Hmm, I'm confused.  I don't see a lua/utils/ directory, much less lua/utils/init.lua.  Is something broken on my system?
