### ISSUE TITLE
Question: Why does this repo not use pcall like Neovim-from-scratch?

### ISSUE THREAD

**Issue by TSoli** [LunarVim/nvim-basic-ide#140]
In the videos for neovim from scratch, Chris makes a point that using pcall is safer since you can just notify errors and it won't completely break your config. In this repo, I can see that pcalls are no longer used much (i.e when requiring plugins) and I was wondering whether this is still safe somehow or whether I should add them in if I use a similar structure. Sorry if this is a bit off topic but I am new to setting up neovim and the communities so I wasn't sure where the best place to post this would be. Thanks!

**Comment by MickTheRus** [comment]
The reason pcalls were used is because packer would completely shit the bed if one of the plugins hasn't been installed. Since each file has the plugin to install we know for sure it's going to be installed and Lazy will not break completely if 1 plugin fails.
