### ISSUE TITLE
After removing project.lua Neovim crashes on start failing load Telescope

### ISSUE THREAD

**Issue by mjmierzwa** [LunarVim/nvim-basic-ide#141]
I used LunarVim configuration without packages responsible for terminal and DAP. It all worked.
After I removed project.lua nvim does not load Telescope at all or if I add `lazy = false` into package configuration it crashes on start of nvim:
```
Failed to load 'plugins.telescope' m:/app/nvim/lua/plugins/telescope.lua:18: module 'telescope.actions' not found:
^Ino filed package.preload['telescope.actions']
...
```

project.lua is deleted and telescope.lua looks like below:
```
local M = {
  "nvim-telescope/telescope.nvim",
  -- commit = "40c31fdde93bcd85aeb3447bb3e2a3208395a868",
  commit = "685bc8e3890d2feb07ccf919522c97f7d33b94e4",
  lazy = false,
  priority = 1000,
  event = "Bufenter",
  cmd = { "Telescope" },
  dependencies = {
    {
      'nvim-lua/plenary.nvim', 
      -- "ahmedkhalf/project.nvim",
      -- commit = "8c6bad7d22eef1b71144b401c9f74ed01526a4fb",
    },
  },
}

local actions = require "telescope.actions"

M.opts = {
  defaults = {
    prompt_prefix = " ",
    selection_caret = " ",
    path_display = { "smart" },
    file_ignore_patterns = { ".git/", "node_modules" },
    mappings = {
      i = {
        ["<Down>"] = actions.move_selection_next,
        ["<Up>"] = actions.move_selection_previous,
        ["<C-j>"] = actions.move_selection_next,
        ["<C-k>"] = actions.move_selection_previous,
      },
    },
  },
}
return M
```
Can those two packages be independent? Where I could get help?
I am working on Windows if that matters.

**Comment by Rishabh672003** [comment]
in the default nvim-basic-ide config i removed `project.nvim` and didnt get any errors,
 so most likely something is wrong with your config

**Comment by mjmierzwa** [comment]
> in the default nvim-basic-ide config i removed `project.nvim` and didnt get any errors,
> so most likely something is wrong with your config

Thank you for taking time to answer. After you removed project.nvim does Telescope loads at all? I think I had to add lazy = false there, but then the error. It looked that telescope was loaded as dependency in project.lua first:
```local M = {
  "ahmedkhalf/project.nvim",
  commit = "685bc8e3890d2feb07ccf919522c97f7d33b94e4",
  dependencies = {
    {
      "nvim-telescope/telescope.nvim",
      commit = "203bf5609137600d73e8ed82703d6b0e320a5f36",
      event = "Bufenter",
      cmd = { "Telescope" },
    },
  },
}
```
Additionally commit version for telescope in telescope.lua and in project.lua dependency telescope differ.
It may be that my problem is of my foult and/or misunderstanding. Sadly at that point I am not able to fix it myself.

**Comment by mjmierzwa** [comment]
Anyway I have rewritten config using Packer. Not because I feel it is better but because at my current level of understanding I can better understand what is happening.
