### ISSUE TITLE
Treesitter not highlighting .tpp files.

### ISSUE THREAD

**Issue by Rz-Rz** [LunarVim/nvim-basic-ide#151]
So I'm writing a lot of c++ code, and I have been using .tpp to store my template integration code. The only problem is that the file are not highlighted, similarly to a .txt file. Everything is plain white. 

I was wondering if there was an elegant solution to the problem, that wouldn't spring a lot of warning, errors and others whatnots..?

I believe that the highlighting change could be done "simply" by specifying to vim that .tpp files are to be treated as c++ files. But it seems to spring some new issues. 

If someone has a way to do it and would provide some code, I would gladly report back as to how it went. 

Thanks in advance.

**Comment by wadeduvall** [comment]
`set filetype=cpp` will do what you want. You could set an autocmd to trigger on filetype *.tpp. This seems to work:

```
autocmd('Filetype', {
  pattern = { 'text', 'markdown', 'html', 'xhtml', 'javascript', 'typescript' },
  command = 'setlocal cc=0'
})
```

**Comment by Rz-Rz** [comment]
it works ! thanks :)
