### ISSUE TITLE
Current version of gitsigns causes CPU spikes on navigation

### ISSUE THREAD

**Issue by callmeBuzzard** [LunarVim/nvim-basic-ide#155]
This affects the version of gitsigns currently in use by the repo:
`commit = "ec4742a7eebf68bec663041d359b95637242b5c3"`.

Navigation would spike cpu usage and lock up the entire desktop for several seconds.  The problem was gitsigns running one git-blame process per line navigation.  A discussion of the problem is here:

https://github.com/lewis6991/gitsigns.nvim/pull/878

It has been fixed to trigger on edit instead of navigation.  Apparently further optimizations are planned but this stopped the cpu spikes for me.

If anyone else is being affected by this, you can go into your gitsigns.lua and comment out the commit property and then run :Lazy or restart nvim to update it.  If that works and you want to keep it, just lock the commit property to the new hash.

**Comment by Rishabh672003** [comment]
i will update the plugin, thanks for the issue
