### ISSUE TITLE
When I open java file I see in lsp info that both jdtls and jdt.ls are available and they both try to do the same operation

### ISSUE THREAD

**Issue by abhijeetsrivastava** [LunarVim/nvim-basic-ide#17]
When I open java file I see in lsp info that both jdtls and jdt.ls are available and they both try to do the same operation and most times I end up with duplicate operations like both of them try to add imports or both of them trying the same operation and none of them succeeding.

![java-nvim-snapshot](https://user-images.githubusercontent.com/20049243/175819247-8b0a9ca8-b1f3-4f82-890e-b8fa0d13c8b1.png)

![code-actions](https://user-images.githubusercontent.com/20049243/175819250-01544825-c681-4676-a611-6357e01a63ee.png)

What should have happened:
only nvim-jdtls should have handled the commands? I wonder if something is missing in my config. I am basically using the same config in this repo (also followed youtube to understand if I needed to do something else)

**Comment by ChristianChiarulli** [comment]
are you using the java ide branch?

**Comment by abhijeetsrivastava** [comment]
I had neovim-from-scratch and then I followed your youtube and used the java-ide branch where I was confused.

If there is nothing obvious, I am going to close java-ide-branch and see if it resolves. Thanks! will update

**Comment by ChristianChiarulli** [comment]
I think you're looking for these two lines:

https://github.com/LunarVim/nvim-basic-ide/blob/492796d86f6a08b5ab7eaac1f8254c693008c924/lua/user/lsp/lsp-installer.lua#L43

https://github.com/LunarVim/nvim-basic-ide/blob/492796d86f6a08b5ab7eaac1f8254c693008c924/lua/user/lsp/lsp-installer.lua#L46

**Comment by abhijeetsrivastava** [comment]
This worked, I didn't have to pull from here. Thanks for awesome content.
