### ISSUE TITLE
lua language server failed.

### ISSUE THREAD

**Issue by scorbin** [LunarVim/nvim-basic-ide#18]
I keep getting the following error, even though i install the lua language server
spawning language server with cmd: 'lua-language-server-failed' the language server is ether not installed or missing in path

How do i check path?

**Comment by pchaos** [comment]
npm install -g lua language server ??

**Comment by ChristianChiarulli** [comment]
@pchaos it's not a npm package.

Make sure you :LspInstallInfo and press `i` on sumneko

**Comment by scorbin** [comment]
That worked, Thanks

**Comment by kobzar** [comment]
> That worked, Thanks

Close the issue please
