### ISSUE TITLE
null-ls not formatting with gofumpt

### ISSUE THREAD

**Issue by dnjmn** [LunarVim/nvim-basic-ide#19]
hii,

null-ls is not working for me...
using builtins.formatting.gofumpt...

can anyone please check if it is working in there system... 

no errors in checkhealth

**Comment by dnjmn** [comment]
--- sorry, stupid mistake

**Comment by dnlmengs** [comment]
hey, @dnjmn, what was it for you? I seem to be exactly there and I'm not being able to see what it is :S

**Comment by dnlmengs** [comment]
ok, mine was asdf messing with the go binaries path and it got fixed it either reinstalling gofumpt or going back to the previous go version

**Comment by dnjmn** [comment]
Dont remember now... was probably a path issue

**Comment by dnlmengs** [comment]
Same here xD
