### ISSUE TITLE
attempt to call field 'setup' (a nil value)

### ISSUE THREAD

**Issue by quaffpotion** [LunarVim/nvim-basic-ide#22]
Compiled neovim 0.7 from source.
Running `nvim` produced:

```
nvim-tree.lua:13: attempt to call field 'setup' (a nil value)
```

Tried to run `:PackerSync` based on the advice of another issue and now I get this:

```
Error detected while processing /Users/XXXX/.config/nvim/init.lua:
E5113: Error while calling lua chunk: ...cker/start/telescope.nvim/lua/telescope/actions/init.lua:34: Key does not exist for 'telescope.actions': cycle_history_next
stack traceback:
        [C]: in function 'error'
        ...cker/start/telescope.nvim/lua/telescope/actions/init.lua:34: in function '__index'
        /Users/XXXX/.config/nvim/lua/user/telescope.lua:18: in main chunk
        [C]: in function 'require'
        /Users/XXXX/.config/nvim/init.lua:7: in main chunk
Press ENTER or type command to continue
```

Any advice on where to begin debugging items like this?

**Comment by quaffpotion** [comment]
This is using the rust branch: `rust-ide-0.7`.

**Comment by kobzar** [comment]
Put :checkhealth here

**Comment by quaffpotion** [comment]
At least for tree-sitter it seems arm is not supported!? `have 'x86_64', need 'arm64e'`

**Comment by quaffpotion** [comment]
Nevermind, at least for tree-sitter we have this: https://github.com/nvim-treesitter/nvim-treesitter/issues/791#issuecomment-843469426

**Comment by quaffpotion** [comment]
Also deleted packer packages
Everything looks good now
