### ISSUE TITLE
E5113: Error while calling lua chunk:

### ISSUE THREAD

**Issue by caamittiwari** [LunarVim/nvim-basic-ide#23]
Error detected while processing /home/amit/.config/nvim/init.lua:
E5113: Error while calling lua chunk: /home/amit/.config/nvim/lua/user/cmp.lua:53: attempt to index field 'preset' (a nil value)
stack traceback:
        /home/amit/.config/nvim/lua/user/cmp.lua:53: in main chunk
        [C]: in function 'require'
        /home/amit/.config/nvim/init.lua:6: in main chunk

this  error   is coming  even  we  use   neovim  version  0.7

**Comment by Rishabh672003** [comment]
old issue should be fixed in V2
