### ISSUE TITLE
How does this compare to LunarVim?

### ISSUE THREAD

**Issue by olalonde** [LunarVim/nvim-basic-ide#25]
Would be helpful to have a comparison with LunarVim to help people decide which one is a best fit.

**Comment by kobzar** [comment]
This repo like template for power vim users and has strong stable pluging using method.
The settings is on many files.
LV is complete for begginers and all the settings store in one config.lua file
Also, LV has the good and big community like discord e.t.c.
So, you must chouse for yourself what is the best for you.

**Comment by olalonde** [comment]
OK thanks, I ended up picking this over LunarVim. Helped me to get rid of my old viml configs :) Just had a bit of trouble getting https://github.com/simrat39/rust-tools.nvim to work seamlessly because it was also messing with lspconfig. Ended up with something like:

`lua/user/rusttools.lua`:

```lua
local status_ok, rust_tools = pcall(require, "rust-tools")
if not status_ok then
	return
end

local opts = {
	-- all the opts to send to nvim-lspconfig
	-- these override the defaults set by rust-tools.nvim
	-- see https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md#rust_analyzer
	server = {
		-- standalone file support
		-- setting it to false may improve startup time
		standalone = true,
		on_attach = require("user.lsp.handlers").on_attach,
		capabilities = require("user.lsp.handlers").capabilities,
		settings = {
			-- to enable rust-analyzer settings visit:
			-- https://github.com/rust-analyzer/rust-analyzer/blob/master/docs/user/generated_config.adoc
			["rust-analyzer"] = {
				-- enable clippy on save
				checkOnSave = {
					command = "clippy",
				},
			},
		},
	}, -- rust-analyer options
}

rust_tools.setup(opts)
```

**Comment by olalonde** [comment]
Ah also had to add `	ignore_install = { "phpdoc" }, -- List of parsers to ignore installing` to `treesitter.lua` cause it wouldn't install on my system (macos arm64).
