### ISSUE TITLE
nvim-treesitter phpdoc parser dependency won't ever install

### ISSUE THREAD

**Issue by apotenza92** [LunarVim/nvim-basic-ide#30]
Hi, every time I open nvim I now see the following:

`[nvim-treesitter] [0/1] Installing NPM dependencies of phpdoc parser`

It never finishes installing, even if I leave it for a while.

**Comment by ncursr** [comment]
So I did a little bit of research into this issue and it seems that [this](https://github.com/claytonrcarter/tree-sitter-phpdoc/pull/2) was resolved by updating node to version 14, but I cannot confirm as my system won't allow updating to 14 for some reason. I just decided to [turn off](https://www.reddit.com/r/neovim/comments/u3hj8p/treesitter_cant_install_phpdoc_on_m1_mac/) phpdoc instead.

**Comment by chas-kane** [comment]
Had the same issue (along with what seems a slew of others) and adding phpdoc to the ignore sections in `treesitter.lua` got rid of the error message for me.
