### ISSUE TITLE
cmp completion table list - rust

### ISSUE THREAD

**Issue by ulrikmonrad** [LunarVim/nvim-basic-ide#34]
Hi,

I've been following your learning rust series.
I noticed when you used "std::XX" you got completions for possible submodules within std such as "std::io, std::fs, std::error" et.c.

I've tried deciphering relevant lua files for where this option/configuration is made, but without any luck so far.

Could anyone possibly point me in the right direction?

**Comment by Rishabh672003** [comment]
you can look through chis' own config https://github.com/christianchiarulli/nvim
and see what he does with lsp and cmp

**Comment by Rishabh672003** [comment]
closing this issue if you need any help ask in the discord, heres the link to join - https://discord.gg/Xb9B4Ny
