### ISSUE TITLE
I do all by instruction, but after run nvim nothing start installs...

### ISSUE THREAD

**Issue by adminoid** [LunarVim/nvim-basic-ide#36]
Mac OS Monterey
What is the reason might be?
Thank you!

**Comment by Yukang-LIAN** [comment]
Hi guys, you can check if  directory `~/.loacl/share/nvim/site/pack/packer/start/packer.nvim` exists. 
If it does, just delete it by 
1. `cd ~/.loacl/share/nvim/site/pack/packer/start`
2. `rm -rf ./packer.nvim`

Then rerun `nvim`, it should reinstall all plugins.
I hope this method can help you.

**Comment by Blingoose** [comment]
Yup. This doesn't work on MacosOS m1 Monterey. Too many errors on start.

**Comment by wuchirat** [comment]
> Hi guys, you can check if directory `~/.loacl/share/nvim/site/pack/packer/start/packer.nvim` exists. If it does, just delete it by
> 
> 1. `cd ~/.loacl/share/nvim/site/pack/packer/start`
> 2. `rm -rf ./packer.nvim`
> 
> Then rerun `nvim`, it should reinstall all plugins. I hope this method can help you.

I did it but still not work.

**Comment by Yukang-LIAN** [comment]
When you execute `nvim`, what is the interface that appears, can you show it?

**Comment by logan271** [comment]
same issue here. i'm on MacosOS m1 Monterey

**Comment by topul** [comment]
E5113: Error while calling lua chunk: .config/nvim/lua/user/lsp/lsp-installer.lua:28: attempt to index a boolean value

**Comment by nebunebu** [comment]
> > Hi guys, you can check if directory `~/.loacl/share/nvim/site/pack/packer/start/packer.nvim` exists. If it does, just delete it by
> > 
> > 1. `cd ~/.loacl/share/nvim/site/pack/packer/start`
> > 2. `rm -rf ./packer.nvim`
> > 
> > Then rerun `nvim`, it should reinstall all plugins. I hope this method can help you.
> 
> I did it but still not work.
 
1. `cd ~/.local/share/nvim/site/pack/packer/start`
2. `rm -rf packer.nvim`
3. `nvim`
4. `:PackerClean` in nvim command mode.
5. `:PackerUpdate` in nvim command mode.
