### ISSUE TITLE
[Question] How to enable tflint.

### ISSUE THREAD

**Issue by rjshrjndrn** [LunarVim/nvim-basic-ide#42]
Hi,
First of all, thank you for this amazing project.

I write a lot of terraform code, and for that, I used COC and tflint.

But here, when I do `LspInstall` I can see tflint, but even after installing that nothing seems to be working. I'm a noob in lua, and configuration based on that. I tried to google pretty much everywhere and nothing of such could be found. So Can you please help me to enable the config?

Note: I tried looking into `lsp/settings/null-ls.lua` but no direct way to import a lint. 

Thank you.

![image](https://user-images.githubusercontent.com/2563385/182839540-7b4599c1-3845-46a5-9488-77509e61cb04.png)
![image](https://user-images.githubusercontent.com/2563385/182839607-6ff3dff6-1a84-4f44-8a27-6c880fe268e9.png)

**Comment by Rishabh672003** [comment]
try it with Realease-0.8
as you have installed tflint, have you added it to lsp/null-ls.lua
if not add this
