### ISSUE TITLE
LSP Error

### ISSUE THREAD

**Issue by ghost** [LunarVim/nvim-basic-ide#44]
I received this error after cloning this repo to setup neovim.
![image](https://user-images.githubusercontent.com/110935937/184412465-404d42ea-c546-4abf-9cba-bfdf674b58ab.png)

A fix for this would be great.

**Comment by Toby222** [comment]
Are you using the right version of neovim?
This setup is for 0.7, not the prerelease builds.

**Comment by Rishabh672003** [comment]
yeah, downgrade your neovim to 0.7 or use my pr #53
