### ISSUE TITLE
[Question] Override plugin variables

### ISSUE THREAD

**Issue by rjshrjndrn** [LunarVim/nvim-basic-ide#5]
First of all, Thank you for this awesmoe project. It's easier to read, understand, and customize. And if you don't want to start everything from scratch, it's a lot of value.

I'm a noob translating my vim language to lua. I'm using [vimwiki](https://github.com/vimwiki/vimwiki) for my note taking purposes. I've tried
```vim
  use { 'vimwiki/vimwiki',
    config = function()
      vim.g.vimwiki_list = {
        {path= '~/vimwiki/', syntax= 'markdown', ext= '.md'},
        {path= '~/vimwiki_personal/', syntax= 'markdown', ext= '.md'}
      }
      vim.g.vimwiki_ext2syntax = {md= 'markdown', mkd= 'markdown', wiki = 'media'}
      vim.g.vimwiki_folding=''
      vim.g.vimwiki_listsyms = ' ○◐●✓'
    end
    }
```

But I want to separate this config as a `vimwiki.lua` like all other plugin configs. I tried a log of combinations, unfortunately, nothing is working. Can you help me out on this ?

**Comment by kobzar** [comment]
Try this
Add this in your init.lua
```
require "user.vimwiki"
```
Add this line in your plugins.lua
```
-- vimwiki
  use { "vimwiki/vimwiki", commit = "63af6e72dd3fa840bffb3ebcb8c96970c02e0913" }
```
Add new file in you lua/user dir with vimwiki.lua
Paste next
local status_ok, vimwiki = pcall(require, "vimwiki")
if not status_ok then
  return
end

vimwiki.setup {
 -- Your uptions here 
}

```

```

**Comment by rjshrjndrn** [comment]
@kobzar Thank you very much for your example. But do you mind giving some elaboration to each step, for my understanding? As I told I'm sooper noob to lua. :( :pray:

**Comment by rjshrjndrn** [comment]
Thank you very much for your example @kobzar :pray: 
Do you mind telling me why we need to add this line? even before adding the plugin?

> Try this Add this in your init.lua
> 
> ```
> require "user.vimwiki"
> ```

And can I use `plugin.setup` for any plugin?

**Comment by kobzar** [comment]
yes. use this trick like a template for any plugin
or look in to LUNARVIM

**Comment by kobzar** [comment]
Could we close this issue?

**Comment by rjshrjndrn** [comment]
Sure. Thanks for your help.

**Comment by rjshrjndrn** [comment]
Hi @kobzar 
Following is my config file for vimwiki.lua. But somehow vimwiki is not loading the config. Do I have to do anything extra?

I've tried, `PackerSync` `PackerCompile` `LuaCacheCleaner`, But No luck...


```lua
local status_ok, vimwiki = pcall(require, "vimwiki")
if not status_ok then
  return
end

vimwiki.config = function()
      vim.g.vimwiki_list = {
        {path= '~/vimwiki/', syntax= 'markdown', ext= '.md'},
        {path= '~/vimwiki_personal/', syntax= 'markdown', ext= '.md'}
      }
      -- Ref: https://stackoverflow.com/questions/65549814/setting-vimwiki-list-in-a-lua-init-file
      -- Check comment in answer

     -- ## Not loading
      vim.g.vimwiki_ext2syntax = {['.md'] = 'markdown', ['.markdown'] = 'markdown', ['.mdown'] = 'markdown'}

      vim.g.vimwiki_folding=''
      vim.g.vimwiki_listsyms = ' ○◐●✓'
   end
```

**Comment by kobzar** [comment]
Check you init.lua and plugins.lua did you add this plugin and config in this files to?

**Comment by rjshrjndrn** [comment]
Yes,  as you suggested.

If I add directly in to the packer config it's working. Ese it's not. 😔

**Comment by kobzar** [comment]
Show you init.lua plugins.lua vimviki.lua and screen of file list and in folder lua/user

**Comment by rjshrjndrn** [comment]
**init.lua**
```lua
require "user.options"
require "user.keymaps"
require "user.plugins"
require "user.autocommands"
require "user.colorscheme"
require "user.cmp"
require "user.telescope"
require "user.treesitter"
require "user.autopairs"
require "user.comment"
require "user.gitsigns"
require "user.nvim-tree"
require "user.bufferline"
require "user.lualine"
require "user.toggleterm"
require "user.project"
require "user.impatient"
require "user.illuminate"
require "user.indentline"
require "user.alpha"
require "user.lsp"
require "user.dap"
require "user.luasnip"
require "user.vimwiki"
```

**plugin.lua**
```lua
  -- vimwiki
  use { 'vimwiki/vimwiki'}
--     config = function()
--       vim.g.vimwiki_list = {
--         {path= '~/vimwiki/', syntax= 'markdown', ext= '.md'},
--         {path= '~/vimwiki_personal/', syntax= 'markdown', ext= '.md'}
--       }
--       vim.g.vimwiki_ext2syntax = {md= 'markdown', mkd= 'markdown', wiki = 'media'}
--       vim.g.vimwiki_folding=''
--       vim.g.vimwiki_listsyms = ' ○◐●✓'
--     end
-- }
```

**vimwiki.lua**
```lua
local status_ok, vimwiki = pcall(require, "vimwiki")
if not status_ok then
  return
end

vimwiki.setup = function()
      vim.g.vimwiki_list = {
        {path= '~/vimwiki/', syntax= 'markdown', ext= '.md'},
        {path= '~/vimwiki_personal/', syntax= 'markdown', ext= '.md'}
      }
      vim.g.vimwiki_ext2syntax = {['.md'] = 'markdown', ['.mkd'] = 'markdown', ['.wiki'] = 'media', ['.rajesh'] = 'markdown'}
      -- vim.g.vimwiki_ext2syntax = { md= 'markdown',
      --     mkd= 'markdown',
      --     wiki = 'media'
      --   }
      vim.g.vimwiki_folding=''
      vim.g.vimwiki_listsyms = ' ○◐●✓'
    end
```

**Comment by kobzar** [comment]
in plugins.lua 
```
use ({"vimwiki/vimwiki", commit = "63af6e72dd3fa840bffb3ebcb8c96970c02e0913"})
```

**Comment by kobzar** [comment]
What must work and how? Explain please step by step that i try to repeat you task.

**Comment by kobzar** [comment]
U dont need it. I show you the full sample.
