### ISSUE TITLE
vscode-css-language-server error: ENOTDIR

### ISSUE THREAD

**Issue by pruf70** [LunarVim/nvim-basic-ide#50]
Hi, I have the following error when trying to open any css file:
"Spawning language server with cmd: `vscode-css-language-server` failed with error message: ENOTDIR: not a directory"

I freshly installed neovim v0.7.2 and pulled the nvim repository.

**Comment by Rishabh672003** [comment]
try it with nvim-basic-ide 0.8 and if the issue persists reopen this issue
