### ISSUE TITLE
looks awesome, but don't know how to use, is there any reference?

### ISSUE THREAD

**Issue by SolskGaer** [LunarVim/nvim-basic-ide#52]

**Comment by mrbrianrt** [comment]
Great learning opportunity for you here.

**Comment by Rishabh672003** [comment]
https://www.youtube.com/playlist?list=PLhoH5vyxr6Qq41NFL4GvhFp-WLd5xzIzZ
this playlist is about setting up the ide but you can watch that to even learn what plugins do

**Comment by Rishabh672003** [comment]
i think this issue will go nowhere so i am closing it
