### ISSUE TITLE
Robotframework-ls not attaching to buffer

### ISSUE THREAD

**Issue by RustyWalters** [LunarVim/nvim-basic-ide#59]
I've installed the lsp: robotframework_ls using the install capability of LspInstallInfo (lsp installer) with neovim 7.  LspInstallInfo shows the server as being installed.   I've also added the server "robotframework_ls" to the list of servers in the lsp-installer.lua file.  However, when I load a file with a dot robot file extension, there is no syntax highlighting and LspInfo shows nothing attached to the buffer.  Any advise would be appreciated.

**Comment by Rishabh672003** [comment]
i dont think there is a treesitter for robot (correct me if i am wrong) so in that aspect we cannot do anything

**Comment by RustyWalters** [comment]
I made the assumption since it was available as a lsp server within 'lsp installer' that it was supported.

**Comment by Rishabh672003** [comment]
it does have a lsp but no tree-sitter, also now try the lsp with 0.8 release and see if it still doesnt connect to the buffer.

**Comment by Rishabh672003** [comment]
closing this issue @RustyWalters , if you still have the issue reopen it
