### ISSUE TITLE
Word highlighting

### ISSUE THREAD

**Issue by floydj** [LunarVim/nvim-basic-ide#71]
Hello there! This isn't an issue per se, but something in this configuration is causing all instances of the word under cursor to be highlighted, which drives me bonkers. But I can't find the plugin or configuration that's enabling it.

Can someone help with that? Many thanks in advance.

<img width="383" alt="image" src="https://user-images.githubusercontent.com/1292970/196696429-7e817a63-725b-4ad1-9b8c-96d7288ef869.png">

**Comment by Rishabh672003** [comment]
its a plugin called illuminate, you can disable it here https://github.com/LunarVim/nvim-basic-ide/blob/fa51853c0890bf9992b6fc880025853772ecbdb0/lua/user/lsp/handlers.lua#L84
just comment out the lines from 84 to 88

**Comment by Rishabh672003** [comment]
https://github.com/LunarVim/nvim-basic-ide/blob/fa51853c0890bf9992b6fc880025853772ecbdb0/lua/user/plugins.lua#L85
here it is in plugins.lua
