### ISSUE TITLE
Telescope/fzf-lua exits neovim upon file selection

### ISSUE THREAD

**Issue by floydj** [LunarVim/nvim-basic-ide#73]
Running into what I find strange behavior:

Using telescope to find a file, I often cancel the search using Escape. But I've noticed that I have to actually press Escape twice for the Telescope popup to close.

Once I do that however, every time I use Telescope in the future to select a file, Neovim exits completely. I can open Telescope, use the arrow keys to navigate the list of files and _then_ select the file and all works ok. But that exiting is pretty annoying.

Is that something anyone else has run into? Or do I have something else wrong here? Thanks in advance!

**Comment by floydj** [comment]
I've actually run into this when using fzf-lua, even without using the double-Esc. It has something to do with this:

https://github.com/LunarVim/nvim-basic-ide/blob/fa51853c0890bf9992b6fc880025853772ecbdb0/lua/user/autocommands.lua#L28

If I comment that out, I don't have problems with exiting nvim under those conditions. As the line seems to indicate, it has something to do with Nvim-tree. The Nvim-tree window is open when I first open neovim.

When I open up inside a project with `nvim .` and instantly try to do a file search w/ fzf-lua, it just exits Vim. 

Any ideas on what's up here? What is the above line trying to accomplish? I can just comment it out, and all goes ok, but seems like there's some functionality I'm missing by doing that.

**Comment by Rishabh672003** [comment]
> What is the above line trying to accomplish? I can just comment it out, and all goes ok, but seems like there's some functionality I'm missing by doing that.

in my knowledge what its for was to quit neovim when there is only one buffer and nvim-tree open an you are focus in the buffer

**Comment by floydj** [comment]
Thank you - it didn't seem to work quite that way for me, but not important with my workflow to have it.
