### ISSUE TITLE
`node` optional or not?

### ISSUE THREAD

**Issue by proofer** [LunarVim/nvim-basic-ide#75]
`README.md` says, "Next we need to install python support (node is optional)" and then three shell commands later it says, "NOTE make sure you have [node](https://nodejs.org/en/) installed". Is `node` optional or required?

**Comment by Rishabh672003** [comment]
both are reffering to dfferent things when it says (node is optional) its referring to node support in neovim which is optional
![image](https://user-images.githubusercontent.com/53911515/197930457-7e673186-f606-4f90-a4ff-963aa244c153.png)

but what the other line about node is necessary is about node being necessary to install lsp's using mason

**Comment by Rishabh672003** [comment]
i think i will update the readme to make it more clear

**Comment by Rishabh672003** [comment]
hope this has cleared your dobts cloding this issue, if you still dont get it reopen this issue
