### ISSUE TITLE
suggestion: move impatient to top in init.lua

### ISSUE THREAD

**Issue by ccbiozhaw** [LunarVim/nvim-basic-ide#78]
hey, thanks for your great work on the starter id, I am enjoying it a lot. I noticed that 

`require "user.impatient"`

is pretty far down in init.lua. If you move it further up you can source it earlier and get a bigger improvement in startup time. this is also what is suggested on the impatient.nvim page:

https://github.com/lewis6991/impatient.nvim

`To use impatient, you need only to include it near the top of your init.lua or init.vim.
`

**Comment by Rishabh672003** [comment]
oh yeah i should do that thanks for the heads up

**Comment by Rishabh672003** [comment]
done
