### ISSUE TITLE
Nerd Fonts Don't Work

### ISSUE THREAD

**Issue by scorbin** [LunarVim/nvim-basic-ide#8]
I am having trouble getting the nerd fonts to work, see below.
I tried running getnf and nothing happens.  I am  running on  ubuntu 20.04.  Is there specific fonts that i need to install?   Everything else works great.  
 

![Screenshot from 2022-06-22 19-35-32](https://user-images.githubusercontent.com/2176302/175196579-002bb3a7-90da-408b-82f9-e9fbfb85669d.png)

**Comment by kobzar** [comment]
First you must add Nerd Fonts in your system
https://github.com/LunarVim/lunarvim.org/blob/master/docs/configuration/04-nerd-fonts.md
or 
https://github.com/ryanoasis/nerd-fonts

The next one, change setting for your terminal app (select the nerd font)
Use normal terminal app like alacritty, kitty e.t.c

**Comment by ChristianChiarulli** [comment]
This is more of a terminal issue than an issue for this repo.

**Comment by kobzar** [comment]
Im on mac - any problem
Iterm2 LunarVim and this repo working fine with glyphs

**Comment by scorbin** [comment]
I did the following with the standard ubuntu terminal and the fonts worked.

```
git clone --depth 1 https://github.com/ryanoasis/nerd-fonts.git
cd nerd-fonts
./install
```

**Comment by ChristianChiarulli** [comment]
@scorbin we good to close this then?

**Comment by scorbin** [comment]
It is good to close, thanks
