### ISSUE TITLE
Jump to the terminal when opening the file

### ISSUE THREAD

**Issue by GenePg** [LunarVim/nvim-basic-ide#81]
https://user-images.githubusercontent.com/20477170/200193703-8843ec44-4e2a-4e71-9a0e-d8ec9d524d5d.mov

**Comment by Rishabh672003** [comment]
remove this line from your config - https://github.com/LunarVim/nvim-basic-ide/blob/0e7a4ad784d93d60e8be686eeb50b53c9e3d65a9/lua/user/autocommands.lua#L28

**Comment by Rishabh672003** [comment]
closing this, if you still have an issue reopen this
