### ISSUE TITLE
Can't get `gf` to work in "init.lua"

### ISSUE THREAD

**Issue by simsrw73** [LunarVim/nvim-basic-ide#86]
Just getting started learning nvim, etc. But I load nvim with this config, hit `c` at the dashboard to open "init.lua", cursor down to one of the require lines and put the cursor on the file name, then type command `gf` and it says it can't find the file. I thought I saw this working in the videos, but don't remember where. It might have been one from a different series? What am I missing?

**Comment by Rishabh672003** [comment]
try doing `gd` that should work, `gf` is a default vim binding that looks for paths similar to one in your cursor while `gd` is a lsp thing that gets you to definitions

**Comment by Rishabh672003** [comment]
also if its annoying for you to use gd, i have a ftplugin file that makes it work 
heres the link for it [link](https://github.com/Rishabh672003/Neovim/blob/main/ftplugin/lua.lua)
place it in ~/.config/nvim/ftplugin/lua.lua

**Comment by simsrw73** [comment]
> try doing `gd` that should work, `gf` is a default vim binding that looks for paths similar to one in your cursor while `gd` is a lsp thing that gets you to definitions

Doh! Got it. That works. So much to learn... Thanks. I'll also check out your plugin.
