### ISSUE TITLE
How to install nvim-navic plugin? 

### ISSUE THREAD

**Issue by dronhund** [LunarVim/nvim-basic-ide#87]
don't sure where to put configuration for navic plugin. 
I tried to add it to M.on_attach function in handlers.lua but it doesn't seem to work.
Can someone help please?

**Comment by Rishabh672003** [comment]
you can take my configs as an example on how you do it, heres it is - [config](https://github.com/Rishabh672003/Neovim/blob/3bf612cd356e4f75f7dfdac70cdaaf8850ae00d4/lua/user/lsp/handlers.lua#L47)
if you want more help just comment here and i will help you

**Comment by dronhund** [comment]
works, thank you very much
