### ISSUE TITLE
Newline Indentation Problem

### ISSUE THREAD

**Issue by YeHW** [LunarVim/nvim-basic-ide#90]
When I open curly braces, the indentation looks like this:
![image](https://user-images.githubusercontent.com/43214065/205547176-435ee0a2-66b3-40cc-80ec-c36e35031652.png)
Is this as expected?

**Comment by Rishabh672003** [comment]
so i guess this is a general problem with neovim so we cant do anything here so closing this now you can reopen this issue if you got anything
