### ISSUE TITLE
LSP go definition shows two same locations in vertical split window

### ISSUE THREAD

**Issue by dongdongbh** [LunarVim/nvim-basic-ide#91]
In lua config file, when I press `gd`, it shows two same locations in vertical split window, but I want it just jump to the file.
![image](https://user-images.githubusercontent.com/11084708/206064531-d7c6fde5-b1e4-4dc8-8073-9003a408322e.png)

**Comment by Rishabh672003** [comment]
if you have any way i can replicate it leave it here otherwise i will close this issue in a month or 2

**Comment by dongdongbh** [comment]
Seems it relates to the lua lsp server, but I can not find out the reason, and it only appear in lua file, and I checked there is only one lua server installed.

**Comment by dongdongbh** [comment]
In addition to this, sometimes there indeed has multiple locations, after I select a location and press `Enter`, I want the split window automatically close, is there a way to do that?

**Comment by dongdongbh** [comment]
@gBopHuk I guess it related with Lua-language-servrr, I created a [issue](https://github.com/sumneko/lua-language-server/issues/1819) there.
