### ISSUE TITLE
lsp_keymaps not loading for null_ls only languages

### ISSUE THREAD

**Issue by garyedwards** [LunarVim/nvim-basic-ide#92]
Hi, thanks for a great project.

I am having an issue where I am trying to use `sqlfuff` with null_ls without a full blown sql language server installed and the `lsp_keymaps` do not load.

I can run `lua vim.diagnostic.open_float()` or `lua vim.lsp.buf.format` manually and it works as expected.  Also the provided `black` setup for python config works without issue.

It looks like loading the keymaps is dependent on `on_attach` for the LS?  If so does null_ls trigger this?

I am still new to lua and nvim so a bit of guidance would be appreciated.

Gary

**Comment by Rishabh672003** [comment]
yeah i have had this issue and also heard it from many people, i dont know why it happens but an easy solution is just moving the keymap from handlers.lua to keymaps.lua
