### ISSUE TITLE
Opening a file through telescope is closing neovim automatically

### ISSUE THREAD

**Issue by ankitvashisht12** [LunarVim/nvim-basic-ide#93]
Whenever I'm trying to open file using telescope ( by `<leader>ff` ), instead of opening the file it's actually closing the neovim automatically. 

https://user-images.githubusercontent.com/40850169/207383869-e424fd36-1bd2-4786-bede-9cb6335c6705.mp4

The issue happening only in the case of fresh start of neovim ( when there is no file that is already opened i.e. no buffer present ). 

As shown in the below video, when the some file is already present in the buffer ( in this case `.gitignore` ) I'm able to open `keymaps.lua` perfectly using telescope.

https://user-images.githubusercontent.com/40850169/207383890-05c48fab-7e5f-482e-b8c8-a6ae22c22ada.mp4

**Comment by monk3yd** [comment]
This also happens when trying to create, edit or remove files within nvim-tree without previously opening a file.

**Comment by Rishabh672003** [comment]
wts causing this is this autocommand which is for quiting nvim when nvim-tree is the only thing opened with other buffer https://github.com/LunarVim/nvim-basic-ide/blob/9d626ef9af01766fce371873f06e564617196749/lua/user/autocommands.lua#L19

**Comment by monk3yd** [comment]
Commented the line and it's fixed. Thank you :D

**Comment by Rishabh672003** [comment]
i tried finding ways to retain this behaviour that is close nvim-tree with the last buffer but have found no way to solve the issue && fix the issue; dont know what to do
