### ISSUE TITLE
Suggestions: Command Palette?

### ISSUE THREAD

**Issue by kiyoon** [LunarVim/nvim-basic-ide#95]
Thanks for the wonderful template. I've been learning a lot using this.
Wouldn't it be nice to have an IDE-style command palette like `LinArcX/telescope-command-palette.nvim`?
It would be good for users to learn new features using this config, and also good for users to expand to their own taste once the template is here.

**Comment by Rishabh672003** [comment]
for now no features will be added to this repo only bug fixes. but yeah i would look into this plugin and if i like it and think it deserves to be here i will ask chris if i could add it in the next release that is of nvim-basic-ide for neovim-0.9
